export const englishIngredients = [
  "abundance",
  "apricots",
  "agar-agar",
  "garlic powder",
  "cranberries",
  "alcohol",
  "almonds",
  "pineapples",
  "Armagnac",
  "artichokes",
  "eggplants",
  "goji berries",
  "bananas",
  "bergamot",
  "beets",
  "butter",
  "peanut butter",
  "baking soda",
  "blue cheese",
  "candy",
  "ladyfingers",
  "beef broth",
  "vegetable broth",
  "fish stock",
  "chicken broth",
  "Boursin",
  "Brie",
  "peanuts",
  "cocoa powder",
  "coffee",
  "Calvados",
  "Camembert",
  "cinnamon",
  "Cantal",
  "starfruit",
  "caramel",
  "carrots",
  "blackcurrants",
  "brown sugar",
  "eggplant caviar",
  "sundried tomato caviar",
  "pepper caviar",
  "celery",
  "celeriac",
  "cherries",
  "cocoa powder",
  "chestnuts",
  "cabbage",
  "Brussels sprouts",
  "cauliflower",
  "red cabbage",
  "green cabbage",
  "bitter lemons",
  "lemons",
  "limes",
  "clementines",
  "cognac",
  "quinces",
  "Comté",
  "coriander",
  "chestnut cream",
  "heavy cream",
  "fresh cream",
  "liquid cream",
  "cumin",
  "turmeric",
  "curry",
  "water",
  "orange blossom water",
  "sparkling water",
  "fresh cheese",
  "flour",
  "whole wheat flour",
  "almond flour",
  "wheat flour",
  "chestnut flour",
  "coconut flour",
  "corn flour",
  "millet flour",
  "spelt flour",
  "lupin flour",
  "chickpea flour",
  "quinoa flour",
  "rice flour",
  "buckwheat flour",
  "rye flour",
  "soy flour",
  "cornstarch",
  "potato starch",
  "tapioca starch",
  "feta",
  "figs",
  "dried figs",
  "strawberries",
  "raspberries",
  "fruits",
  "passion fruit",
  "veal stock",
  "chicken stock",
  "fish stock",
  "cheese",
  "cottage cheese",
  "spreadable cream cheese",
  "gelatin powder",
  "gin",
  "ginger",
  "gorgonzola",
  "guavas",
  "pomegranates",
  "grenadine",
  "currants",
  "Gruyère",
  "beans",
  "white beans",
  "red beans",
  "green beans",
  "oil",
  "sweet almond oil",
  "peanut oil",
  "hemp oil",
  "coconut oil",
  "rapeseed oil",
  "linseed oil",
  "hazelnut oil",
  "walnut oil",
  "palm oil",
  "grape seed oil",
  "sesame oil",
  "soy oil",
  "sunflower oil",
  "olive oil",
  "pineapple juice",
  "beetroot juice",
  "carrot juice",
  "lemon juice",
  "cranberry juice",
  "fruit juice",
  "kiwi juice",
  "grapefruit juice",
  "apple juice",
  "grape juice",
  "tomato juice",
  "orange juice",
  "persimmons",
  "ketchup",
  "Kiri",
  "kirsch",
  "kiwis",
  "kumquats",
  "milk",
  "almond milk",
  "oat milk",
  "goat milk",
  "coconut milk",
  "powdered milk",
  "soy milk",
  "rice milk",
  "cow's milk",
  "bay leaves",
  "baking sourdough",
  "yeast",
  "lychees",
  "Madeira",
  "tangerines",
  "mangoes",
  "mascarpone",
  "mayonnaise",
  "mint",
  "honey",
  "mirabelle plums",
  "Morbier cheese",
  "mustard",
  "Munster cheese",
  "blackberries",
  "nutmeg",
  "blueberries",
  "hazelnuts",
  "walnuts",
  "cashews",
  "coconut",
  "macadamia nuts",
  "pecans",
  "Brazil nuts",
  "onion powder",
  "oranges",
  "bitter oranges",
  "oregano",
  "grapefruits",
  "papayas",
  "parsnips",
  "paprika",
  "parmesan",
  "pastis",
  "pâté",
  "spreadable paste",
  "curry paste",
  "black olive paste",
  "green olive paste",
  "peaches",
  "pine nuts",
  "Espelette pepper",
  "Cayenne pepper",
  "sweet pepper",
  "pistachios",
  "pears",
  "peas",
  "split peas",
  "chickpeas",
  "ground white pepper",
  "Cayenne pepper",
  "ground black pepper",
  "bell peppers",
  "apples",
  "potatoes",
  "port",
  "flan powder",
  "carob powder",
  "pea protein",
  "rice protein",
  "soy protein",
  "whey protein",
  "prunes",
  "plums",
  "almond butter",
  "quetsches",
  "raclette cheese",
  "radishes",
  "grapes",
  "raisins",
  "reblochon cheese",
  "reine-claude plums",
  "rum",
  "ricotta",
  "salmon rillettes",
  "tuna rillettes",
  "chicken rillettes",
  "pork rillettes",
  "duck rillettes",
  "rosemary",
  "rooibos",
  "roquefort cheese",
  "saffron",
  "sweet and sour sauce",
  "barbecue sauce",
  "chili sauce",
  "curry sauce",
  "nuoc-mâm sauce",
  "pesto sauce",
  "soy sauce",
  "tamari sauce",
  "teriyaki sauce",
  "tomato sauce",
  "sea salt",
  "fine salt",
  "Himalayan pink salt",
  "syrup",
  "agave syrup",
  "glucose syrup",
  "maple syrup",
  "spirulina",
  "powdered stevia",
  "cane sugar",
  "coconut sugar",
  "powdered sugar",
  "icing sugar",
  "brown sugar",
  "vanilla sugar",
  "tapenade",
  "tequila",
  "terrine",
  "tea",
  "thyme",
  "tome cheese",
  "Jerusalem artichokes",
  "vanilla powder",
  "wine",
  "vinegar",
  "balsamic vinegar",
  "white vinegar",
  "apple cider vinegar",
  "raspberry vinegar",
  "honey vinegar",
  "rice vinegar",
  "white wine vinegar",
  "red wine vinegar",
  "sherry vinegar",
  "white wine",
  "red wine",
  "vodka",
  "whisky",
  "garlic",
  "Swiss chard",
  "broccoli",
  "cep mushrooms",
  "mushrooms",
  "cucumbers",
  "pickles",
  "squash",
  "zucchini",
  "dates",
  "shallots",
  "emmental cheese",
  "endives",
  "spinach",
  "salad leaves",
  "broad beans",
  "herbal tea",
  "lettuces",
  "lentils",
  "liqueur",
  "yam",
  "melons",
  "turnips",
  "nectarines",
  "onions",
  "orgeat syrup",
  "sorrel",
  "watermelons",
  "sweet potatoes",
  "red kuri squash",
  "pumpkins",
  "salad",
  "escargot lettuce",
  "tomatoes",
  "morel mushrooms",
  "chanterelle mushrooms",
  "oyster mushrooms",
  "shiitake mushrooms",
  "truffle",
  "meat",
  "beef",
  "lamb",
  "chicken",
  "turkey",
  "rabbit",
  "mutton",
  "kid goat",
  "duck",
  "duck breast",
  "pork",
  "capon",
  "goose",
  "foie gras",
  "wild boar",
  "deer",
  "chop",
  "steak",
  "ground beef",
  "escalope",
  "fillets",
  "roast",
  "sausages",
  "black pudding",
  "minced meat",
  "paupiettes",
  "crépinettes",
  "trout",
  "salmon",
  "tuna",
  "whiting",
  "bass",
  "dorade",
  "sole",
  "cod",
  "salted cod",
  "sardines",
  "mackerel",
  "ling",
  "red mullet",
  "codfish",
  "shrimp",
  "scallops",
  "squid",
  "cuttlefish",
  "octopus",
  "mussels",
  "clams",
  "crab",
  "lumpfish roe",
  "caviar",
  "oysters",
  "olives",
  "green olives",
  "black olives",
  "eggs",
  "quail eggs",
  "chocolate",
  "dark chocolate",
  "milk chocolate",
  "white chocolate",
  "hot chocolate",
  "sauce",
  "chocolate sauce",
  "caramel sauce",
  "bread",
  "baguette",
  "whole wheat bread",
  "cornbread",
  "brioche",
  "jam",
  "gelée",
  "ice cream",
  "sorbet",
  "pasta",
  "spaghetti",
  "cannelloni",
  "tagliatelle",
  "ravioli",
  "macaroni",
  "penne",
  "lasagna",
  "rice",
  "basmati rice",
  "brown rice",
  "rice noodles",
  "black rice",
  "thai rice",
  "noodles",
  "udon noodles",
  "soba noodles",
  "vermicelli",
  "wild rice",
  "sticky rice",
  "polenta",
  "bulgur",
  "quinoa",
  "slivered almonds",
  "vanilla pods",
  "sunflower seeds",
  "chia seeds",
  "pumpkin seeds",
  "sesame seeds",
  "flax seeds",
  "basil",
  "parsley",
  "dill",
  "miso",
  "kimchi",
  "sauerkraut",
  "tofu",
  "speculoos",
  "petit beurre biscuits",
  "zest",
  "molasses",
  "golden syrup",
  "wheat",
];
