export const frenchIngredients = [
  "abondance",
  "abricots",
  "agar-agar",
  "ail en poudre",
  "airelles",
  "alcool",
  "amandes",
  "ananas",
  "armagnac",
  "artichauts",
  "aubergines",
  "baies de goji",
  "bananes",
  "bergamotes",
  "betteraves",
  "beurre",
  "beurre de cacahuètes",
  "bicarbonate de soude",
  "bleu",
  "bonbons",
  "boudoirs",
  "bouillon de boeuf",
  "bouillon de légumes",
  "bouillon de poisson",
  "bouillon de volaille",
  "boursin",
  "brie",
  "cacahuètes",
  "cacao en poudre",
  "café",
  "calvados",
  "camembert",
  "cannelle",
  "cantal",
  "caramboles",
  "caramel",
  "carottes",
  "cassis",
  "cassonade",
  "caviar d'aubergines",
  "caviar de tomates séchées",
  "caviar de poivrons",
  "céleri",
  "céleris-raves",
  "cerises",
  "chocolat en poudre",
  "châtaignes",
  "choux",
  "choux de Bruxelles",
  "choux-fleurs",
  "choux rouges",
  "choux verts",
  "citrons amers",
  "citrons",
  "citrons verts",
  "clémentines",
  "cognac",
  "coings",
  "comté",
  "coriandre",
  "crème de marrons",
  "crème épaisse",
  "crème fraîche",
  "crème liquide",
  "cumin",
  "curcuma",
  "curry",
  "eau",
  "eau de fleur d'oranger",
  "eau gazeuse",
  "faisselle",
  "farine",
  "farine complète",
  "farine d'amande",
  "farine de blé",
  "farine de châtaigne",
  "farine de coco",
  "farine de maïs",
  "farine de millet",
  "farine d'épeautre",
  "farine de lupin",
  "farine de pois chiche",
  "farine de quinoa",
  "farine de riz",
  "farine de sarrasin",
  "farine de seigle",
  "farine de soja",
  "fécule de maïs",
  "fécule de pomme de terre",
  "fécule de tapioca",
  "féta",
  "figues",
  "figues sèches",
  "fraises",
  "framboises",
  "fruits",
  "fruits de la passion",
  "fond de veau",
  "fond de volaille",
  "fond de poisson",
  "fromage",
  "fromage blanc",
  "fromage frais à tartiner",
  "gélatine en poudre",
  "gin",
  "gingembre",
  "gorgonzola",
  "goyaves",
  "grenades",
  "grenadine",
  "groseilles",
  "gruyère",
  "haricots",
  "haricots blancs",
  "haricots rouges",
  "haricots verts",
  "huile",
  "huile d'amande douce",
  "huile d'arachide",
  "huile de chanvre",
  "huile de coco",
  "huile de colza",
  "huile de lin",
  "huile de noisette",
  "huile de noix",
  "huile de palme",
  "huile de pépins de raisin",
  "huile de sésame",
  "huile de soja",
  "huile de tournesol",
  "huile d'olive",
  "jus d'ananas",
  "jus de betterave",
  "jus de carotte",
  "jus de citron",
  "jus de cranberry",
  "jus de fruits",
  "jus de kiwi",
  "jus de pamplemousse",
  "jus de pomme",
  "jus de raisin",
  "jus de tomate",
  "jus d'orange",
  "kakis",
  "ketchup",
  "kiri",
  "kirsch",
  "kiwis",
  "kumquats",
  "lait",
  "lait d'amande",
  "lait d'avoine",
  "lait de chèvre",
  "lait de coco",
  "lait en poudre",
  "lait de soja",
  "lait de riz",
  "lait de vache",
  "laurier",
  "levain en poudre",
  "levure",
  "litchis",
  "madère",
  "mandarines",
  "mangues",
  "mascarpone",
  "mayonnaise",
  "menthe",
  "miel",
  "mirabelles",
  "morbier",
  "moutarde",
  "munster",
  "mûres",
  "muscade",
  "myrtilles",
  "noisettes",
  "noix",
  "noix de cajou",
  "noix de coco",
  "noix de macadamia",
  "noix de pécan",
  "noix du Brésil",
  "oignon en poudre",
  "oranges",
  "oranges amères",
  "origan",
  "pamplemousses",
  "papayes",
  "panais",
  "paprika",
  "parmesan",
  "pastis",
  "pâté",
  "pâte à tartiner",
  "pâte de curry",
  "pâte d'olive noire",
  "pâte d'olive verte",
  "pêches",
  "pignons",
  "piment d'Espelette",
  "piment de Cayenne",
  "piment doux",
  "pistaches",
  "poires",
  "pois",
  "pois cassés",
  "pois chiches",
  "poivre blanc moulu",
  "poivre de Cayenne",
  "poivre noir moulu",
  "poivrons",
  "pommes",
  "pommes de terre",
  "porto",
  "poudre à flan",
  "poudre de caroube",
  "protéine de pois",
  "protéine de riz",
  "protéine de soja",
  "protéine de whey",
  "pruneaux",
  "prunes",
  "purée d'amande",
  "quetsches",
  "raclette",
  "radis",
  "raisins",
  "raisins secs",
  "reblochon",
  "reines-claudes",
  "rhum",
  "ricotta",
  "rillettes de saumon",
  "rillettes de thon",
  "rillettes de poulet",
  "rillettes de porc",
  "rillettes de canard",
  "romarin",
  "rooibos",
  "roquefort",
  "safran",
  "sauce aigre-douce",
  "sauce barbecue",
  "sauce chili",
  "sauce curry",
  "sauce nuoc-mâm",
  "sauce pesto",
  "sauce soja",
  "sauce tamari",
  "sauce teriyaki",
  "sauce tomate",
  "sel de mer",
  "sel fin",
  "sel rose de l'Himalaya",
  "sirop",
  "sirop d'agave",
  "sirop de glucose",
  "sirop d'érable",
  "spiruline",
  "stevia en poudre",
  "sucre de canne",
  "sucre de coco",
  "sucre en poudre",
  "sucre glace",
  "sucre roux",
  "sucre vanillé",
  "tapenade",
  "tequila",
  "terrine",
  "thé",
  "thym",
  "tome",
  "topinambours",
  "vanille en poudre",
  "vin",
  "vinaigre",
  "vinaigre balsamique",
  "vinaigre blanc",
  "vinaigre de cidre",
  "vinaigre de framboise",
  "vinaigre de miel",
  "vinaigre de riz",
  "vinaigre de vin blanc",
  "vinaigre de vin rouge",
  "vinaigre de xérès",
  "vin blanc",
  "vin rouge",
  "vodka",
  "whisky",
  "ail",
  "blettes",
  "brocolis",
  "cèpes",
  "champignons",
  "concombres",
  "cornichons",
  "courge",
  "courgettes",
  "dattes",
  "échalotes",
  "emmental",
  "endives",
  "épinards",
  "feuilles de salade",
  "fèves",
  "infusion",
  "laitues",
  "lentilles",
  "liqueur",
  "ignames",
  "melons",
  "navets",
  "nectarines",
  "oignons",
  "orgeat",
  "oseille",
  "pastèques",
  "patates douces",
  "potimarrons",
  "potirons",
  "salade",
  "scaroles",
  "tomates",
  "morilles",
  "girolles",
  "pleurotes",
  "shiitakes",
  "truffe",
  "viande",
  "boeuf",
  "agneau",
  "poulet",
  "dinde",
  "lapin",
  "mouton",
  "chevreau",
  "canard",
  "magret de canard",
  "porc",
  "chapon",
  "oie",
  "foie gras",
  "sanglier",
  "cerf",
  "côtelette",
  "steak",
  "steak haché",
  "escalope",
  "filets",
  "rôti",
  "saucisses",
  "boudin",
  "viande hachée",
  "paupiettes",
  "crépinettes",
  "truite",
  "saumon",
  "thon",
  "merlans",
  "bar",
  "dorades",
  "sole",
  "morue",
  "morue salée",
  "sardines",
  "maquereaux",
  "lieue",
  "rougets",
  "cabillaud",
  "crevettes",
  "coquilles Saint-Jacques",
  "calamar",
  "seiche",
  "poulpe",
  "moules",
  "palourdes",
  "crabe",
  "oeufs de lump",
  "caviar",
  "huîtres",
  "olives",
  "olives vertes",
  "olives noires",
  "oeufs",
  "oeufs de caille",
  "chocolat",
  "chocolat noir",
  "chocolat au lait",
  "chocolat blanc",
  "chocolat chaud",
  "coulis",
  "coulis de chocolat",
  "coulis de caramel",
  "pain",
  "baguette",
  "pain complet",
  "pain au maïs",
  "brioche",
  "confiture",
  "gelée",
  "glace",
  "sorbet",
  "pâtes",
  "spaghetti",
  "cannelloni",
  "tagliatelles",
  "ravioli",
  "macaroni",
  "penne",
  "lasagnes",
  "riz",
  "riz basmati",
  "riz complet",
  "nouilles de riz",
  "riz noir",
  "riz thaï",
  "nouilles",
  "nouilles udon",
  "nouilles soba",
  "vermicelles",
  "riz sauvage",
  "riz gluant",
  "polenta",
  "bulgur",
  "quinoa",
  "amandes effilées",
  "gousses de vanille",
  "graines de tournesol",
  "graines de chia",
  "graines de courge",
  "graines de sésame",
  "graines de lin",
  "basilic",
  "persil",
  "aneth",
  "miso",
  "kimchi",
  "choucroute",
  "tofu",
  "spéculoos",
  "petits beurres",
  "zeste",
  "blé",
];
